[package]
name = "hanabi"
version = "0.1.0"
authors = ["Chris Evans <cevans3326@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
thiserror = "1.0"
lazy_static = "1.4.0"
rand = "0.7.3"

[[bin]]
name = "main"
path = "apps/main.rs"
